### ISSUE TITLE
Include "previous" link in transaction paging, and remove "order"?

### ISSUE THREAD

**Issue by thejollyrogers** [stellar/horizon#24]
Do we really need the "order" query parameter in /transactions. It seems to me that keeping it descending (that is, most recent transaction first) is suitable and less confusing.

For example, given an account transaction list in desending order:
[
  txn3,
  txn2,
  txn1
]
Next() should always return more recent transactions starting with paging token txn3, and previous should always return older transactions starting with paging token txn1. IMO adding the order option makes things more confusing and is unnecessary.

**Comment by MonsieurNicolas** [comment]
Not sure what the exact use cases are but if the APIs are going to be used by automation, chronological order is the one it probably wants as it allows to compute balance over time and do cross account reconciliation.

Also it seems to me that chronological order is the simplest one to understand for queries that try to access history since a specific time point.

Of course the paging order should be consistent with the order rows are returned within a page.

-----Original Message-----

**Comment by thejollyrogers** [comment]
I don't see computing balance over time as a popular use case, and I'm not sure what you mean by cross account reconciliation.

I think the far more popular use case for this API is for transaction history, which in every app I've ever used for transaction history is reverse chronological order (you only care about your latest transactions). It is for this use case I think the default (and only) ordering option should be asc.

**Comment by MonsieurNicolas** [comment]
It's fine to go with the simplest API for now if it's not a pain to add the other behavior later. The main challenge with data access APIs like this one is to build something that enables people do do things you didn't necessarily anticipate and not have one API per scenario.

-----Original Message-----

**Comment by nullstyle** [comment]
Think of order as defining 2 things:
- In the absence of a `cursor` parameter, it defines where you start traversing the collection (asc == start of collection, chronologically, desc == end of collection chronologically)
- The direction the requester is traversing the collection.

I prefer the existing design.  IMO, it is only confusing because we are in process of writing the documentation.
